### ISSUE TITLE
Add-ons management

### ISSUE THREAD

**Issue by markb-trustifi** [heroku/heroku-cli-addons-admin#56]
Is it possible to:
- Delete add-on
- Clone add-on with all documents and other data
- Change add-on ID

If there exists only a http request without CLI command it also will be OK.

P.S. All questions are related to add-ons in https://addons-next.heroku.com/addons, not to the add-ons connected to applications.

**Comment by mathias** [comment]
@markb-trustifi The answer to all of these is no. Add-on slugs are immutable: https://devcenter.heroku.com/articles/add-on-partner-technical-best-practices#add-on-slugs-and-plan-slugs-cannot-change
